spring:
    application:
        name: Amtrak-Unofficial-Schedule

server:
    port: 8081

schedule:
    general:
        font:
            family: "Helvetica"
            primary-color: "#002436"
            secondary-color: "#fff"
    header:
        font:
            primary-color: "#ffffff"
            background-color: "#005983"
    direction:
        font:
            font-size: "24"
            primary-color: "#faa634"
    timetable:
        time:
            font:
                font-size: "12"
                primary-color: "#000000"
        station-major:
            font:
                font-size: "14"
                primary-color: "#005581"
        station-minor:
            font:
                font-size: "12"
                primary-color: "#005581"
        station-alt:
            font:
                font-size: "12"
                primary-color: "#000000"

amtrak:
    retry-enabled: true
    data:
        schema:             http
        host:               //localhost:8080
        path:               /v1/route?ids=%d
        web-client:
            connectionTimeoutInMilliseconds: 60000
            responseTimeoutInMilliseconds: 60000
            readTimeoutInMilliseconds: 60000
            writeTimeoutInMilliseconds: 60000
        retry:
            maxRetryCount: 1
            delay: 1000
            maxDelay: 10000
            multiplier: 1.2